# Generated by Django 3.2.25 on 2026-01-31 12:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent department for tree structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.department')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('default_salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('employment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('department', models.ForeignKey(help_text='Department this employee belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.department')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.role')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ('full_name', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='core_employ_departm_7f9313_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['role'], name='core_employ_role_id_11c197_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employment_date'], name='core_employ_employm_b3034c_idx'),
        ),
    ]
